/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package orcle01;

import dao.SawonImple;
import dao.SawonInter;
import dto.SawonDTO;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.List;
/**
 *
 * @author bit
 */
public class Sawon extends javax.swing.JFrame {
    /**
     * Creates new form Sawon
     */
    private void printSawonList(){
        SawonInter dao = SawonImple.getSawondao();
        List<SawonDTO> list = dao.getListSawon(searchValue.getText().trim());
        StringBuffer sb=new StringBuffer();
        for(SawonDTO rs : list){
                sb.append("사원번호 : ").append(rs.getSabun()).append("\n");
                sb.append("이름 : ").append(rs.getSaname()).append("\n");
                sb.append("부서번호 : ").append(rs.getDeptno()).append("\n");
                sb.append("급여 : ").append(rs.getSapay()).append("\n");
                sb.append("입사일 : ").append(rs.getSahire()).append("\n");
        }
        resv.setText(sb.toString());
    }

        public Sawon() {
        initComponents();
         printSawonList();
//        String sql1 = "select sabun,saname,deptno,sapay,sahire from sawon where saname like ? order by 1 desc";
//        Connection con = null;
//        PreparedStatement pstm = null;
//        ResultSet rs = null;
//        //select 일 경우 cursor를 반환
//        try{
//            // 1.Connection 연결
//            con = ConnDriver.getMyConnection();
//            System.out.println("연결성공" + con);
//            pstm = con.prepareStatement(sql1);
//            pstm.setString(1, "%%");
//            rs = pstm.executeQuery();
//            StringBuffer sb = new StringBuffer();
//            while(rs.next()){
//                //sabun,saname,deptno,sapay,sahire
//                sb.append("사원번호 : ").append(rs.getInt("sabun")).append("\n");
//                sb.append("이름 : ").append(rs.getString("saname")).append("\n");
//                sb.append("부서번호 : ").append(rs.getInt("deptno")).append("\n");
//                sb.append("급여 : ").append(rs.getInt("sapay")).append("\n");
//                sb.append("입사일 : ").append(rs.getString("sahire")).append("\n");
//            }
//            resv.setText(sb.toString());
//        }catch(SQLException ex){
//            ex.printStackTrace();
//        }finally{
//            try{
//                if(con!=null){
//                    con.close();
//                }
//            }catch(SQLException ex){
//                ex.printStackTrace();
//            }
//        }
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        resv = new javax.swing.JTextArea();
        searchValue = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(102, 0, 255));

        resv.setColumns(20);
        resv.setRows(5);
        jScrollPane1.setViewportView(resv);

        jButton1.setText("검색");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 624, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(searchValue, javax.swing.GroupLayout.PREFERRED_SIZE, 568, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(60, 60, 60))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
              printSawonList();

        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sawon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sawon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sawon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sawon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Sawon().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea resv;
    private javax.swing.JTextField searchValue;
    // End of variables declaration//GEN-END:variables
}
